import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/global.css";

// Symbols
import "material-symbols";

const spoqaHanSans = localFont({
  src: [
    {
      weight: "400",
      path: "./SpoqaHanSansNeo-Regular.woff2",
    },
    {
      weight: "500",
      path: "./SpoqaHanSansNeo-Medium.woff2",
    },
    {
      weight: "700",
      path: "./SpoqaHanSansNeo-Bold.woff2",
    },
  ]
})

export const metadata: Metadata = {
  title: "맥주",
  description: "Generated by 🍺 beer power",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={spoqaHanSans.className}>{children}</body>
    </html>
  );
}
